[features]
seeds = false
[programs.localnet]
core_game = "A9KvbP1zccZRUYcTjyCYQJ7n1iWKBcR8yDeGTj3mDphV"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
# wallet = "/home/pbibersteinintern/.config/solana/id.json"
wallet = "./tests/test_orchestrator_keypair.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/core_game.ts"


[[test.genesis]]
address = "Bridge1p5gheXUvJ6jGWGeCsgPKgnE3YgdGKRVCMY9o"
program = "./tests/core_bridge.so"

[[test.validator.account]]
address = "FKoMTctsC7vJbEqyRiiPskPnuQx2tX1kurmvWByq5uZP"
filename = "./tests/bridge_config.json"

[[test.validator.account]]
address = "6MxkvoEwgB9EqQRLNhvYaPGhfcLtBtpBqdQugr3AZUgD"
filename = "./tests/guardian_set.json"

[[test.validator.account]]
address = "GXBsgBD3LDn3vkRZF6TfY5RqgajVZ4W5bMAdiAaaUARs"
filename = "./tests/fee_collector.json"


[[test.genesis]]
address = "B6RHG3mfcckmrYN1UhmJzyS1XX3fZKbkeUcpJe9Sy3FE"
program = "./tests/token_bridge.so"

[[test.validator.account]]
address = "3GwVs8GSLdo4RUsoXTkGQhojauQ1sXcDNjm7LSDicw19"
filename = "./tests/token_config.json"

